POST http://localhost:3001/api/clients
content-type: application/json

{
    "fullName": "Adil Rochdi",
    "phone": "0612548796",
    "email":"rochdi@gmail.com",
    "purchaseDate": "01548754",
    "city": "agadir",
    "address": "addresss"
}

###

GET http://localhost:3001/api/clients
Content-Type: application/json
